# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'armgui_ik.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1251, 617)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labels1 = QtWidgets.QLabel(self.centralwidget)
        self.labels1.setGeometry(QtCore.QRect(720, 80, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        self.labels1.setFont(font)
        self.labels1.setObjectName("labels1")
        self.labels2 = QtWidgets.QLabel(self.centralwidget)
        self.labels2.setGeometry(QtCore.QRect(720, 110, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        self.labels2.setFont(font)
        self.labels2.setObjectName("labels2")
        self.labels3 = QtWidgets.QLabel(self.centralwidget)
        self.labels3.setGeometry(QtCore.QRect(720, 140, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        self.labels3.setFont(font)
        self.labels3.setObjectName("labels3")
        self.MplWidget = MplWidget(self.centralwidget)
        self.MplWidget.setEnabled(True)
        self.MplWidget.setGeometry(QtCore.QRect(10, 10, 661, 551))
        self.MplWidget.setMouseTracking(True)
        self.MplWidget.setTabletTracking(True)
        self.MplWidget.setObjectName("MplWidget")
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset.setGeometry(QtCore.QRect(1020, 70, 161, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_reset.setFont(font)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.labels2_ik = QtWidgets.QLabel(self.centralwidget)
        self.labels2_ik.setGeometry(QtCore.QRect(720, 310, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.labels2_ik.setFont(font)
        self.labels2_ik.setObjectName("labels2_ik")
        self.labels1_ik = QtWidgets.QLabel(self.centralwidget)
        self.labels1_ik.setGeometry(QtCore.QRect(720, 280, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.labels1_ik.setFont(font)
        self.labels1_ik.setObjectName("labels1_ik")
        self.labels3_ik = QtWidgets.QLabel(self.centralwidget)
        self.labels3_ik.setGeometry(QtCore.QRect(720, 340, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.labels3_ik.setFont(font)
        self.labels3_ik.setObjectName("labels3_ik")
        self.label_ik = QtWidgets.QLabel(self.centralwidget)
        self.label_ik.setGeometry(QtCore.QRect(730, 230, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ik.setFont(font)
        self.label_ik.setObjectName("label_ik")
        self.doubleSpinBox1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox1.setGeometry(QtCore.QRect(910, 80, 62, 22))
        self.doubleSpinBox1.setAccelerated(True)
        self.doubleSpinBox1.setMinimum(0.0)
        self.doubleSpinBox1.setMaximum(180.0)
        self.doubleSpinBox1.setObjectName("doubleSpinBox1")
        self.doubleSpinBox2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox2.setGeometry(QtCore.QRect(910, 110, 62, 22))
        self.doubleSpinBox2.setAccelerated(True)
        self.doubleSpinBox2.setMinimum(-90.0)
        self.doubleSpinBox2.setMaximum(90.0)
        self.doubleSpinBox2.setObjectName("doubleSpinBox2")
        self.doubleSpinBox3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox3.setGeometry(QtCore.QRect(910, 140, 62, 22))
        self.doubleSpinBox3.setAccelerated(True)
        self.doubleSpinBox3.setMinimum(-90.0)
        self.doubleSpinBox3.setMaximum(90.0)
        self.doubleSpinBox3.setObjectName("doubleSpinBox3")
        self.label_fk = QtWidgets.QLabel(self.centralwidget)
        self.label_fk.setGeometry(QtCore.QRect(730, 30, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_fk.setFont(font)
        self.label_fk.setObjectName("label_fk")
        self.doubleSpinBox_ik1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_ik1.setGeometry(QtCore.QRect(917, 280, 62, 22))
        self.doubleSpinBox_ik1.setAccelerated(True)
        self.doubleSpinBox_ik1.setMinimum(-99.0)
        self.doubleSpinBox_ik1.setObjectName("doubleSpinBox_ik1")
        self.doubleSpinBox_ik2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_ik2.setGeometry(QtCore.QRect(917, 310, 62, 22))
        self.doubleSpinBox_ik2.setAccelerated(True)
        self.doubleSpinBox_ik2.setObjectName("doubleSpinBox_ik2")
        self.doubleSpinBox_ik3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_ik3.setGeometry(QtCore.QRect(917, 340, 62, 22))
        self.doubleSpinBox_ik3.setAccelerated(True)
        self.doubleSpinBox_ik3.setObjectName("doubleSpinBox_ik3")
        self.pushButton_runik = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_runik.setGeometry(QtCore.QRect(1020, 300, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_runik.setFont(font)
        self.pushButton_runik.setObjectName("pushButton_runik")
        self.labels3_2 = QtWidgets.QLabel(self.centralwidget)
        self.labels3_2.setGeometry(QtCore.QRect(720, 170, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        self.labels3_2.setFont(font)
        self.labels3_2.setObjectName("labels3_2")
        self.label_j4 = QtWidgets.QLabel(self.centralwidget)
        self.label_j4.setGeometry(QtCore.QRect(830, 170, 61, 21))
        self.label_j4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_j4.setObjectName("label_j4")
        self.label_x4 = QtWidgets.QLabel(self.centralwidget)
        self.label_x4.setGeometry(QtCore.QRect(830, 280, 61, 21))
        self.label_x4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_x4.setObjectName("label_x4")
        self.label_y4 = QtWidgets.QLabel(self.centralwidget)
        self.label_y4.setGeometry(QtCore.QRect(830, 310, 61, 21))
        self.label_y4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_y4.setObjectName("label_y4")
        self.label_z4 = QtWidgets.QLabel(self.centralwidget)
        self.label_z4.setGeometry(QtCore.QRect(830, 340, 61, 21))
        self.label_z4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_z4.setObjectName("label_z4")
        self.label_iks = QtWidgets.QLabel(self.centralwidget)
        self.label_iks.setGeometry(QtCore.QRect(830, 260, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_iks.setFont(font)
        self.label_iks.setObjectName("label_iks")
        self.label_iks_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_iks_2.setGeometry(QtCore.QRect(920, 260, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_iks_2.setFont(font)
        self.label_iks_2.setObjectName("label_iks_2")
        self.pushButton_rand = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_rand.setGeometry(QtCore.QRect(1020, 260, 161, 31))
        self.pushButton_rand.setObjectName("pushButton_rand")
        self.label_j3 = QtWidgets.QLabel(self.centralwidget)
        self.label_j3.setGeometry(QtCore.QRect(830, 140, 61, 21))
        self.label_j3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_j3.setObjectName("label_j3")
        self.label_j1 = QtWidgets.QLabel(self.centralwidget)
        self.label_j1.setGeometry(QtCore.QRect(830, 80, 61, 21))
        self.label_j1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_j1.setObjectName("label_j1")
        self.label_iks_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_iks_3.setGeometry(QtCore.QRect(830, 60, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_iks_3.setFont(font)
        self.label_iks_3.setObjectName("label_iks_3")
        self.label_j2 = QtWidgets.QLabel(self.centralwidget)
        self.label_j2.setGeometry(QtCore.QRect(830, 110, 61, 21))
        self.label_j2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_j2.setObjectName("label_j2")
        self.label_iks_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_iks_4.setGeometry(QtCore.QRect(910, 60, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_iks_4.setFont(font)
        self.label_iks_4.setObjectName("label_iks_4")
        self.pushButton_browse = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browse.setGeometry(QtCore.QRect(720, 400, 171, 71))
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.label_filename = QtWidgets.QLabel(self.centralwidget)
        self.label_filename.setGeometry(QtCore.QRect(720, 480, 461, 71))
        self.label_filename.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_filename.setWordWrap(True)
        self.label_filename.setObjectName("label_filename")
        self.pushButton_runflie = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_runflie.setGeometry(QtCore.QRect(1000, 400, 181, 71))
        self.pushButton_runflie.setObjectName("pushButton_runflie")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1251, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labels1.setText(_translate("MainWindow", "Joint 1 Angle:"))
        self.labels2.setText(_translate("MainWindow", "Joint 2 Angle:"))
        self.labels3.setText(_translate("MainWindow", "Joint 3 Angle:"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))
        self.labels2_ik.setText(_translate("MainWindow", "Y Axes: "))
        self.labels1_ik.setText(_translate("MainWindow", "X Axes: "))
        self.labels3_ik.setText(_translate("MainWindow", "Z Axes: "))
        self.label_ik.setText(_translate("MainWindow", "PINJ Inverse Kinematics"))
        self.label_fk.setText(_translate("MainWindow", "DH-Forward Kinematics"))
        self.pushButton_runik.setText(_translate("MainWindow", "Run IK"))
        self.labels3_2.setText(_translate("MainWindow", "Joint 4 Angle:"))
        self.label_j4.setText(_translate("MainWindow", "TextLabel"))
        self.label_x4.setText(_translate("MainWindow", "TextLabel"))
        self.label_y4.setText(_translate("MainWindow", "TextLabel"))
        self.label_z4.setText(_translate("MainWindow", "TextLabel"))
        self.label_iks.setText(_translate("MainWindow", "Real Pos"))
        self.label_iks_2.setText(_translate("MainWindow", "Target Pos"))
        self.pushButton_rand.setText(_translate("MainWindow", "Random Target"))
        self.label_j3.setText(_translate("MainWindow", "TextLabel"))
        self.label_j1.setText(_translate("MainWindow", "TextLabel"))
        self.label_iks_3.setText(_translate("MainWindow", "Real Pos."))
        self.label_j2.setText(_translate("MainWindow", "TextLabel"))
        self.label_iks_4.setText(_translate("MainWindow", "Target Pos."))
        self.pushButton_browse.setText(_translate("MainWindow", "Browse File (.csv)"))
        self.label_filename.setText(_translate("MainWindow", "<html>\n"
"    <head/>\n"
"        \n"
"    \n"
"    <body><p>Path name</p>\n"
"    </body>\n"
"</html>"))
        self.pushButton_runflie.setText(_translate("MainWindow", "Run File"))
from mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
